from django.core.management.base import BaseCommand
from vans.models import Van

class Command(BaseCommand):
    help = 'Import van data'

    def handle(self, *args, **kwargs):
        if Van.objects.exists():
            self.stdout.write(self.style.WARNING("Vans already imported — skipping"))
            return
        
        vans_data = [
            {
                "name": "Mobility IeV3",
                "category": "light-duty",
                "tagline": "Smart urban electric mover for last-mile logistics.",
                "images": ["red-auto.webp", "Tez-cyan.webp", "3wheel-carrier.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "fast",
                "range_km": 300,
                "power_kw": 90,
                "battery_capacity_kwh": 45,
                "payload_ton": 1.2,
                "price": 350000,
                "is_featured": False,
                "is_wishlisted": False
            },
            {
                "name": "Jupiter Tez",
                "category": "light-duty",
                "tagline": "Agile and efficient electric delivery solution.",
                "images": ["Jupiter-Tez-brown.webp"],
                "status": "pre-order",
                "badge": "Pre-Order",
                "badge_color": "red",
                "charging_type": "standard",
                "range_km": 250,
                "power_kw": 70,
                "battery_capacity_kwh": 38,
                "payload_ton": 1.0,
                "price": 420000,
                "is_featured": False,
                "is_wishlisted": False
            },
            {
                "name": "EVall e-ZEO V1",
                "category": "light-duty",
                "tagline": "Compact and powerful four-wheeler for urban fleets.",
                "images": ["Tez-cyan.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "fast",
                "range_km": 400,
                "power_kw": 120,
                "battery_capacity_kwh": 65,
                "payload_ton": 2.0,
                "price": 720000,
                "is_featured": True,
                "is_wishlisted": False
            },
            {
                "name": "EVall Ace EV",
                "category": "light-duty",
                "tagline": "Rugged performance for mid-range commercial operations.",
                "images": ["3wheel-carrier.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "fast",
                "range_km": 500,
                "power_kw": 150,
                "battery_capacity_kwh": 80,
                "payload_ton": 3.5,
                "price": 940000,
                "is_featured": False,
                "is_wishlisted": False
            },
            {
                "name": "Titan Haul Pro",
                "category": "medium-duty",
                "tagline": "High-endurance electric hauler built for tough tasks.",
                "images": ["4wheel-LR.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "fast",
                "range_km": 550,
                "power_kw": 180,
                "battery_capacity_kwh": 100,
                "payload_ton": 5.5,
                "price": 1350000,
                "is_featured": True,
                "is_wishlisted": False
            },
            {
                "name": "Voltix CargoMax",
                "category": "heavy-duty",
                "tagline": "Powerful all-electric truck for industrial logistics.",
                "images": ["4wheel-XLR.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "fast",
                "range_km": 600,
                "power_kw": 250,
                "battery_capacity_kwh": 120,
                "payload_ton": 7.0,
                "price": 1890000,
                "is_featured": True,
                "is_wishlisted": False
            },
            {
                "name": "NeoMover E2",
                "category": "light-duty",
                "tagline": "Light and nimble — perfect for intra-city operations.",
                "images": ["3wheel-HL-SV.webp"],
                "status": "pre-order",
                "badge": "Pre-Order",
                "badge_color": "red",
                "charging_type": "standard",
                "range_km": 220,
                "power_kw": 65,
                "battery_capacity_kwh": 30,
                "payload_ton": 0.8,
                "price": 310000,
                "is_featured": False,
                "is_wishlisted": False
            },
            {
                "name": "Tranz EV500",
                "category": "medium-duty",
                "tagline": "Built for sustainable mid-range cargo delivery.",
                "images": ["4wheel-LR.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "standard",
                "range_km": 450,
                "power_kw": 160,
                "battery_capacity_kwh": 90,
                "payload_ton": 4.0,
                "price": 1170000,
                "is_featured": False,
                "is_wishlisted": False
            },
            {
                "name": "LoadX E-Truck",
                "category": "heavy-duty",
                "tagline": "High-capacity transporter for large-scale deliveries.",
                "images": ["4wheel-XLR.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "fast",
                "range_km": 580,
                "power_kw": 230,
                "battery_capacity_kwh": 110,
                "payload_ton": 6.5,
                "price": 1780000,
                "is_featured": False,
                "is_wishlisted": False
            },
            {
                "name": "MetroGo Lite",
                "category": "light-duty",
                "tagline": "Compact delivery van for urban micro logistics.",
                "images": ["3wheel-HL.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "standard",
                "range_km": 180,
                "power_kw": 55,
                "battery_capacity_kwh": 28,
                "payload_ton": 1.0,
                "price": 340000,
                "is_featured": False,
                "is_wishlisted": False
            },
            {
                "name": "TorqueLine Max",
                "category": "heavy-duty",
                "tagline": "Electric powerhouse for industrial-grade transport.",
                "images": ["4wheel-LR.webp"],
                "status": "available",
                "badge": "Available",
                "badge_color": "green",
                "charging_type": "fast",
                "range_km": 600,
                "power_kw": 270,
                "battery_capacity_kwh": 130,
                "payload_ton": 7.0,
                "price": 1900000,
                "is_featured": True,
                "is_wishlisted": False
            },
            {
                "name": "EcoTrek Ranger",
                "category": "medium-duty",
                "tagline": "Reliable and cost-efficient EV for daily cargo needs.",
                "images": ["4wheel-XLR.webp"],
                "status": "pre-order",
                "badge": "Pre-Order",
                "badge_color": "red",
                "charging_type": "standard",
                "range_km": 370,
                "power_kw": 130,
                "battery_capacity_kwh": 70,
                "payload_ton": 3.2,
                "price": 880000,
                "is_featured": False,
                "is_wishlisted": False
            }
        ]
        
        for van_data in vans_data:
            Van.objects.create(**van_data)
        
        self.stdout.write(self.style.SUCCESS(f'Successfully imported {len(vans_data)} vans'))