# Generated by Django 5.2.7 on 2025-11-26 06:44

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Blog post title (max 255 characters)', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated if left blank)', max_length=280, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (recommended 150-160 characters)', max_length=160)),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Main blog content with rich formatting', null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for blog preview/card (recommended: 1200x630px)', null=True, upload_to='blog_featured/%Y/%m/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (SEO & accessibility)', max_length=255)),
                ('featured_image_caption', models.CharField(blank=True, help_text='Optional caption for featured image', max_length=255)),
                ('author', models.CharField(default='Admin', help_text='Author name', max_length=150)),
                ('category', models.CharField(choices=[('electronic-vehicles', 'Electronic Vehicles'), ('technological-advancements', 'Technological Advancements'), ('events', 'Events'), ('news', 'News'), ('reviews', 'Reviews'), ('services', 'Services')], db_index=True, default='news', help_text='Select blog category', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., tesla, charging, battery)', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Publication status', max_length=10)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Mark as featured to highlight on homepage')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Publication date/time (auto-set when published)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.IntegerField(default=0, help_text='Estimated reading time in minutes (auto-calculated)')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this post has been viewed')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='blogs_blogp_publish_52e789_idx'), models.Index(fields=['status', '-published_at'], name='blogs_blogp_status_54e32c_idx'), models.Index(fields=['category', '-published_at'], name='blogs_blogp_categor_bfc576_idx')],
            },
        ),
    ]
