# Generated by Django 5.2.7 on 2025-11-07 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_performance', models.JSONField(blank=True, default=dict)),
                ('sales_service_experience', models.JSONField(blank=True, default=dict)),
                ('open_feedback', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('vehicle_type', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('consent1', models.BooleanField(default=False)),
                ('consent2', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealershipEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(max_length=64)),
                ('alternate_number', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('current_business', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('proposed_territory', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_turnover', models.BigIntegerField(blank=True, null=True)),
                ('investment_capacity', models.BigIntegerField(blank=True, null=True)),
                ('infrastructure', models.JSONField(blank=True, default=list)),
                ('reason_for_interest', models.TextField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=64)),
                ('alternate_number', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('vehicle_types', models.JSONField(blank=True, default=list)),
                ('vehicle_other', models.CharField(blank=True, max_length=255, null=True)),
                ('applications', models.JSONField(blank=True, default=list)),
                ('application_other', models.CharField(blank=True, max_length=255, null=True)),
                ('fleet_size', models.CharField(blank=True, max_length=128, null=True)),
                ('timeline', models.CharField(blank=True, max_length=128, null=True)),
                ('procurement_mode', models.CharField(blank=True, max_length=128, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDriveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('selected_models', models.JSONField(blank=True, default=list)),
                ('other_model', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_time_slot', models.CharField(blank=True, max_length=128, null=True)),
                ('business_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('business_segment_other', models.CharField(blank=True, max_length=255, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('test_drive_date', models.DateField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
