# Generated by Django 5.2.7 on 2025-11-07 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdrivebooking',
            name='other_model',
        ),
        migrations.RemoveField(
            model_name='testdrivebooking',
            name='preferred_time_slot',
        ),
        migrations.RemoveField(
            model_name='testdrivebooking',
            name='selected_models',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='vehicle_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='time_slot',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='vehicle_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='vehicle_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='contact_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='model_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='open_feedback',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='raw_payload',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='sales_service_experience',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='vehicle_performance',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='vehicle_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='contact_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='raw_payload',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='vehicle_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='alternate_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='contact_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='current_business',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='experience',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='firm_turnover',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='infrastructure',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='investment_capacity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='other_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='pincode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='proposed_territory',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='raw_payload',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='reason_for_interest',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dealershipenquiry',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='alternate_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='application_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='applications',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='contact_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='fleet_size',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='procurement_mode',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='raw_payload',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='timeline',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='vehicle_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestdemo',
            name='vehicle_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='business_segment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='business_segment_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='contact_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='raw_payload',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='test_drive_date',
            field=models.DateField(null=True),
        ),
    ]
