# Generated by Django 5.2.7 on 2025-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('light-duty', 'Light Duty'), ('medium-duty', 'Medium Duty'), ('heavy-duty', 'Heavy Duty')], max_length=20)),
                ('tagline', models.CharField(max_length=200)),
                ('images', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pre-order', 'Pre-Order')], default='available', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=20)),
                ('badge_color', models.CharField(blank=True, max_length=20)),
                ('charging_type', models.CharField(choices=[('fast', 'Fast'), ('standard', 'Standard')], default='fast', max_length=20)),
                ('range_km', models.PositiveIntegerField(help_text='Range in kilometers')),
                ('power_kw', models.PositiveIntegerField(help_text='Power in kilowatts')),
                ('battery_capacity_kwh', models.PositiveIntegerField(help_text='Battery capacity in kWh')),
                ('payload_ton', models.DecimalField(decimal_places=1, help_text='Payload in tons', max_digits=4)),
                ('price', models.PositiveIntegerField(help_text='Price in rupees')),
                ('currency', models.CharField(default='₹', max_length=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_wishlisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vans',
                'ordering': ['-created_at'],
            },
        ),
    ]
