# Generated by Django 5.2.7 on 2025-12-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(db_index=True, help_text="Unique page identifier from navMenuData (e.g., 'home', 'company-overview')", max_length=100, unique=True)),
                ('page_path', models.CharField(db_index=True, help_text="URL path for this page (e.g., '/', '/what-drives-us/company-overview')", max_length=255)),
                ('page_name', models.CharField(help_text='Human-readable page name for admin reference', max_length=150)),
                ('page_title', models.CharField(help_text='Browser tab title (recommended: 50-60 characters)', max_length=70)),
                ('meta_description', models.CharField(help_text='SEO meta description (recommended: 150-160 characters)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text="Comma-separated keywords (e.g., 'electric vehicles, EV, commercial')", max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to prevent duplicate content issues', max_length=500)),
                ('og_title', models.CharField(help_text='Open Graph title (recommended: 60-90 characters)', max_length=95)),
                ('og_description', models.CharField(help_text='Open Graph description (recommended: 150-200 characters)', max_length=200)),
                ('og_type', models.CharField(choices=[('website', 'Website'), ('article', 'Article'), ('product', 'Product')], default='website', help_text='Open Graph content type', max_length=20)),
                ('og_url', models.URLField(help_text='Open Graph URL (full absolute URL)', max_length=500)),
                ('og_image_url', models.URLField(help_text='Open Graph image URL (recommended: 1200x630px, CDN hosted)', max_length=500)),
                ('og_image_alt', models.CharField(blank=True, help_text='Alt text for OG image (accessibility)', max_length=255)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=30)),
                ('twitter_title', models.CharField(help_text='Twitter card title', max_length=70)),
                ('twitter_description', models.CharField(help_text='Twitter card description', max_length=200)),
                ('twitter_image_url', models.URLField(help_text='Twitter card image URL (recommended: 1200x628px, CDN hosted)', max_length=500)),
                ('twitter_image_alt', models.CharField(blank=True, help_text='Alt text for Twitter image (accessibility)', max_length=255)),
                ('twitter_site', models.CharField(blank=True, help_text='Twitter handle of website (e.g., @evall_india)', max_length=50)),
                ('twitter_creator', models.CharField(blank=True, help_text='Twitter handle of content creator', max_length=50)),
                ('robots_meta', models.CharField(default='index, follow', help_text="Robots meta tag (e.g., 'index, follow', 'noindex, nofollow')", max_length=100)),
                ('structured_data', models.JSONField(blank=True, help_text='JSON-LD structured data for rich snippets', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable/disable SEO tags for this page')),
                ('priority', models.IntegerField(default=10, help_text='Priority for fallback hierarchy (higher = more important)')),
                ('notes', models.TextField(blank=True, help_text='Internal notes for content team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'SEO Tag',
                'verbose_name_plural': 'SEO Tags',
                'ordering': ['-priority', 'page_id'],
                'indexes': [models.Index(fields=['page_id'], name='seo_seotag_page_id_d6ed40_idx'), models.Index(fields=['page_path'], name='seo_seotag_page_pa_bf3ab4_idx'), models.Index(fields=['is_active', '-priority'], name='seo_seotag_is_acti_7b3edd_idx')],
            },
        ),
    ]
