# Generated by Django 5.2.7 on 2025-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_site_verification', models.TextField(blank=True, help_text='Google Site Verification meta tag content (e.g., <meta name="google-site-verification" content="your-code">)')),
                ('header_script', models.TextField(blank=True, help_text='Scripts to be added in <head> section (e.g., Google Analytics, Meta Pixel)')),
                ('footer_script', models.TextField(blank=True, help_text='Scripts to be added before </body> closing tag (e.g., Chat widgets, Additional tracking)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Advanced SEO Setting',
                'verbose_name_plural': 'Advanced SEO Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='seotag',
            options={'ordering': ['page_id'], 'verbose_name': 'SEO Tag', 'verbose_name_plural': 'SEO Tags'},
        ),
        migrations.RemoveIndex(
            model_name='seotag',
            name='seo_seotag_is_acti_7b3edd_idx',
        ),
        migrations.RemoveField(
            model_name='seotag',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seotag',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='seotag',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='seotag',
            name='structured_data',
        ),
        migrations.RemoveField(
            model_name='seotag',
            name='twitter_creator',
        ),
        migrations.RemoveField(
            model_name='seotag',
            name='twitter_image_alt',
        ),
        migrations.RemoveField(
            model_name='seotag',
            name='twitter_site',
        ),
        migrations.AddField(
            model_name='seotag',
            name='schema',
            field=models.JSONField(blank=True, help_text='JSON-LD structured data for rich snippets', null=True),
        ),
    ]
